#EXAMPLE
#QUERY = 'db.names.find({name: "John Doe"})'

FIRST_QUERY = 'db.users.insertOne({name: "Ashwin Kumar", email: "ashwinvx@gmail.com"})'
SECOND_QUERY = 'db.movies.find({directors: "Christopher Nolan"})'
THIRD_QUERY = 'db.movies.find({genres: "Action"}).sort({year:-1})'
FOURTH_QUERY = 'db.movies.find({"imdb.rating": {$gt : 8}}, {title:1, imdb:1})'
FIFTH_QUERY = 'db.movies.find({cast: {$all: ["Tom Hanks", "Tim Allen"]}})'
SIXTH_QUERY = 'db.movies.find({cast:  ["Tom Hanks", "Tim Allen"]})'
SEVENTH_QUERY = 'db.movies.find({genres:"Comedy", directors: "Steven Spielberg"})'
EIGTH_QUERY = 'db.movies.updateOne({title: "The Matrix"},{$set: {available_on:"Sflix"}})'
NINETH_QUERY = 'db.movies.updateOne({title: "The Matrix"},{$inc: {metacritic: 1}})'
TENTH_QUERY = 'db.movies.updateMany({year: 1997}, {$push: {genres: "Gen Z"}})'
ELEVENTH_QUERY = 'db.movies.updateMany({"imdb.rating":{$lt:5}},{$inc:{"imdb.rating":1}})'
TWELVETH_QUERY = 'db.comments.deleteOne({_id : {$exists:true}})'
THIRTEENTH_QUERY = 'db.comments.deleteMany({author: "The Matrix"})'
FOURTEENTH_QUERY = 'db.movies.deleteMany({genres: {$exists:false}})'
FIVETEENTH_QUERY = 'db.movies.aggregate([{$group: { _id: "$year", count: { $sum: 1 }}},{$sort: {_id:1}}])'
SIXTEENTH_QUERY = 'db.movies.aggregate([{$group: { _id: "$directors", averageRating: { $avg: "$imdb.rating" }}},{$sort: {averageRating:-1}}])'